<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerF90x9uv\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerF90x9uv/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerF90x9uv.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerF90x9uv\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerF90x9uv\App_KernelProdContainer([
    'container.build_hash' => 'F90x9uv',
    'container.build_id' => '7930a603',
    'container.build_time' => 1736584147,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerF90x9uv');
